name: BunnyFamily
version: ${project.version}
main: com.berneymark.bunnyfamily.BunnyFamily
api-version: 1.13
authors: [MarkBerney]
description: Custom plugin to manage my own server.
website: berneymark.com
commands:
  craft:
    description: Craft on the go!
    usage: /<command>
  heal:
    description: Health to the max!
    usage: /<command>
  feed:
    description: Food to the max!
    usage: /<command>
    aliases: [feedme]
  god:
    description: The powers of the almighty!
    usage: /<command>
  print:
    description: Test my config.yml!
    usage: /<command>